/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.Control;
import DTO.Alumno;
import DTO.Materia;
import DTO.Matricula;
import java.sql.Date;

/**
 *
 * @author kevin
 */
public class Formulario extends javax.swing.JFrame {
    private Control c;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        c=new Control();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Alumno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        btnBuscarA = new javax.swing.JButton();
        btnGuardarA = new javax.swing.JButton();
        btnActualizarA = new javax.swing.JButton();
        btnEliminarA = new javax.swing.JButton();
        Materia = new javax.swing.JPanel();
        lbliDMateria = new javax.swing.JLabel();
        lblNameMateria = new javax.swing.JLabel();
        lblProfesorMateria = new javax.swing.JLabel();
        lblCreditosMateria = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        txtProfesorMateria = new javax.swing.JTextField();
        btnBuscarMateria = new javax.swing.JButton();
        btnActualizarMateria = new javax.swing.JButton();
        btnGuardarMateria = new javax.swing.JButton();
        btnEliminarMateria = new javax.swing.JButton();
        txtCreditosMateria = new javax.swing.JTextField();
        Matricula = new javax.swing.JPanel();
        lbliDMatricula = new javax.swing.JLabel();
        lbliDAlumnoMatricula = new javax.swing.JLabel();
        lbliDMateriaMatricula = new javax.swing.JLabel();
        lblFechaMatricula = new javax.swing.JLabel();
        txtidMatricula = new javax.swing.JTextField();
        txtidAlumnoMatricula = new javax.swing.JTextField();
        txtidMateriaMatricula = new javax.swing.JTextField();
        txtFechaMatricula = new javax.swing.JTextField();
        btnBuscarMatricula = new javax.swing.JButton();
        btnGuardarMatricula = new javax.swing.JButton();
        btnActualizarMatricula = new javax.swing.JButton();
        btnEliminarM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)), "REGISTRAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N

        Alumno.setBackground(new java.awt.Color(204, 204, 204));
        Alumno.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel1.setText("IdAlumno");

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel5.setText("Genero");

        txtAlumno.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        txtApellido.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        txtGenero.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });

        btnBuscarA.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnBuscarA.setText("Buscar");
        btnBuscarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAActionPerformed(evt);
            }
        });

        btnGuardarA.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnGuardarA.setText("Guardar");
        btnGuardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAActionPerformed(evt);
            }
        });

        btnActualizarA.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnActualizarA.setText("Actualizar");
        btnActualizarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAActionPerformed(evt);
            }
        });

        btnEliminarA.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnEliminarA.setText("Eliminar");
        btnEliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlumnoLayout = new javax.swing.GroupLayout(Alumno);
        Alumno.setLayout(AlumnoLayout);
        AlumnoLayout.setHorizontalGroup(
            AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlumnoLayout.createSequentialGroup()
                        .addComponent(btnGuardarA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(btnActualizarA)
                        .addGap(54, 54, 54)
                        .addComponent(btnEliminarA))
                    .addGroup(AlumnoLayout.createSequentialGroup()
                        .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(55, 55, 55)
                        .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAlumno)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtEmail)
                            .addComponent(txtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarA)))
                .addGap(27, 27, 27))
        );
        AlumnoLayout.setVerticalGroup(
            AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarA))
                .addGap(27, 27, 27)
                .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarA)
                    .addComponent(btnActualizarA)
                    .addComponent(btnEliminarA))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("ALUMNO", Alumno);

        Materia.setBackground(new java.awt.Color(204, 204, 204));
        Materia.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        Materia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbliDMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lbliDMateria.setText("IdMateria");

        lblNameMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lblNameMateria.setText("Nombre");

        lblProfesorMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lblProfesorMateria.setText("Profesor");

        lblCreditosMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lblCreditosMateria.setText("Creditos");

        txtMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        txtNombreMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        txtProfesorMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        btnBuscarMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnBuscarMateria.setText("Buscar");
        btnBuscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMateriaActionPerformed(evt);
            }
        });

        btnActualizarMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnActualizarMateria.setText("Actualizar");
        btnActualizarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMateriaActionPerformed(evt);
            }
        });

        btnGuardarMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnGuardarMateria.setText("Guardar");
        btnGuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMateriaActionPerformed(evt);
            }
        });

        btnEliminarMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnEliminarMateria.setText("Eliminar");
        btnEliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMateriaActionPerformed(evt);
            }
        });

        txtCreditosMateria.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        javax.swing.GroupLayout MateriaLayout = new javax.swing.GroupLayout(Materia);
        Materia.setLayout(MateriaLayout);
        MateriaLayout.setHorizontalGroup(
            MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MateriaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MateriaLayout.createSequentialGroup()
                        .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreditosMateria)
                            .addComponent(lblNameMateria)
                            .addComponent(lbliDMateria))
                        .addGap(38, 38, 38)
                        .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMateria)
                            .addComponent(txtNombreMateria, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProfesorMateria)
                            .addComponent(txtCreditosMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarMateria)
                        .addGap(43, 43, 43))
                    .addGroup(MateriaLayout.createSequentialGroup()
                        .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfesorMateria)
                            .addGroup(MateriaLayout.createSequentialGroup()
                                .addComponent(btnGuardarMateria)
                                .addGap(48, 48, 48)
                                .addComponent(btnActualizarMateria)
                                .addGap(49, 49, 49)
                                .addComponent(btnEliminarMateria)))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        MateriaLayout.setVerticalGroup(
            MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MateriaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbliDMateria)
                    .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarMateria)))
                .addGap(29, 29, 29)
                .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameMateria)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesorMateria)
                    .addComponent(txtProfesorMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreditosMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditosMateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(MateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarMateria)
                    .addComponent(btnGuardarMateria)
                    .addComponent(btnEliminarMateria))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("MATERIA", Materia);

        Matricula.setBackground(new java.awt.Color(204, 204, 204));
        Matricula.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));

        lbliDMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lbliDMatricula.setText("IdMatricula");

        lbliDAlumnoMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lbliDAlumnoMatricula.setText("IdAlumno");

        lbliDMateriaMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lbliDMateriaMatricula.setText("IdMateria");

        lblFechaMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lblFechaMatricula.setText("Fecha ");

        txtidMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        txtidMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidMatriculaActionPerformed(evt);
            }
        });

        txtidAlumnoMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        txtidAlumnoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidAlumnoMatriculaActionPerformed(evt);
            }
        });

        txtidMateriaMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        txtFechaMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N

        btnBuscarMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnBuscarMatricula.setText("Buscar");
        btnBuscarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMatriculaActionPerformed(evt);
            }
        });

        btnGuardarMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnGuardarMatricula.setText("Guardar");
        btnGuardarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMatriculaActionPerformed(evt);
            }
        });

        btnActualizarMatricula.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnActualizarMatricula.setText("Actualizar");
        btnActualizarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMatriculaActionPerformed(evt);
            }
        });

        btnEliminarM.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        btnEliminarM.setText("Eliminar");
        btnEliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MatriculaLayout = new javax.swing.GroupLayout(Matricula);
        Matricula.setLayout(MatriculaLayout);
        MatriculaLayout.setHorizontalGroup(
            MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatriculaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbliDMatricula)
                    .addComponent(lbliDAlumnoMatricula)
                    .addComponent(lbliDMateriaMatricula)
                    .addComponent(lblFechaMatricula)
                    .addComponent(btnGuardarMatricula))
                .addGap(46, 46, 46)
                .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MatriculaLayout.createSequentialGroup()
                        .addComponent(btnActualizarMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarM)
                        .addGap(32, 32, 32))
                    .addGroup(MatriculaLayout.createSequentialGroup()
                        .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidMatricula)
                            .addComponent(txtidAlumnoMatricula)
                            .addComponent(txtidMateriaMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtFechaMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnBuscarMatricula)
                        .addGap(24, 24, 24))))
        );
        MatriculaLayout.setVerticalGroup(
            MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatriculaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbliDMatricula)
                    .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarMatricula)))
                .addGap(25, 25, 25)
                .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbliDAlumnoMatricula)
                    .addComponent(txtidAlumnoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbliDMateriaMatricula)
                    .addComponent(txtidMateriaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaMatricula)
                    .addComponent(txtFechaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMatricula)
                    .addComponent(btnActualizarMatricula)
                    .addComponent(btnEliminarM))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("MATRICULA", Matricula);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAActionPerformed
        // TODO add your handling code here:
        Alumno a = new Alumno();
        a.setIdAlumno(Integer.parseInt(txtAlumno.getText()));
        a.setNombre(txtNombre.getText());
        a.setApellido(txtApellido.getText());
        a.setEmail(txtEmail.getText());
        a.setGenero(txtGenero.getText());
        // Control c = new Control();
        c.registrar(a,null,null);
    }//GEN-LAST:event_btnGuardarAActionPerformed

    private void btnBuscarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAActionPerformed
        // TODO add your handling code here:
        Alumno a = c.buscarAlumno(Integer.parseInt(txtAlumno.getText()));
        txtNombre.setText(a.getNombre());
        txtApellido.setText(a.getApellido());
        txtEmail.setText(String.valueOf(a.getEmail()));
        txtGenero.setText(String.valueOf(a.getGenero()));
    }//GEN-LAST:event_btnBuscarAActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtidAlumnoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidAlumnoMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidAlumnoMatriculaActionPerformed

    private void txtidMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidMatriculaActionPerformed

    private void btnGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateriaActionPerformed
        // TODO add your handling code here:
        Materia m = new Materia();
        m.setIdMateria(Integer.parseInt(txtMateria.getText()));
        m.setNombre(txtNombreMateria.getText());
        m.setProfesor(txtProfesorMateria.getText());
        m.setCreditos(txtCreditosMateria.getText());
        // Control c = new Control();
        c.registrar(null,m,null);
    }//GEN-LAST:event_btnGuardarMateriaActionPerformed

    private void btnGuardarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMatriculaActionPerformed
        // TODO add your handling code here:
        Matricula mt = new Matricula();
        mt.setIdMatricula(Integer.parseInt(txtidMatricula.getText()));
        mt.setIdAlumno(Integer.parseInt(txtidAlumnoMatricula.getText()));
        mt.setIdMateria(Integer.parseInt(txtidMateriaMatricula.getText()));
        mt.setFechaMatricula(Date.valueOf(txtFechaMatricula.getText()));
        // Control c = new Control();
        c.registrar(null,null,mt);
    }//GEN-LAST:event_btnGuardarMatriculaActionPerformed

    private void btnBuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMateriaActionPerformed
        // TODO add your handling code here:
        Materia m = c.buscarMateria(Integer.parseInt(txtMateria.getText()));
        txtNombreMateria.setText(m.getNombre());
        txtProfesorMateria.setText(m.getProfesor());
        txtCreditosMateria.setText(String.valueOf(m.getCreditos()));
    }//GEN-LAST:event_btnBuscarMateriaActionPerformed

    private void btnBuscarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMatriculaActionPerformed
        // TODO add your handling code here:
        Matricula mt = c.buscarMatricula(Integer.parseInt(txtidMatricula.getText()));
        txtidAlumnoMatricula.setText( String.valueOf(mt.getIdAlumno()));
        txtidMateriaMatricula.setText(String.valueOf(mt.getIdMateria()));
        txtFechaMatricula.setText(String.valueOf(mt.getFechaMatricula()));
    }//GEN-LAST:event_btnBuscarMatriculaActionPerformed

    private void btnActualizarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMatriculaActionPerformed
        // TODO add your handling code here:
        if(txtidMatricula.getText().length()>0 && txtidAlumnoMatricula.getText().length()>0 && txtidMateriaMatricula.getText().length()>0 && txtFechaMatricula.getText().length()>0){
        c.actualizarMt(Integer.parseInt(txtidMatricula.getText()),Integer.parseInt(txtidAlumnoMatricula.getText()), Integer.parseInt(txtidMateriaMatricula.getText()), Date.valueOf(txtFechaMatricula.getText()));
        }
    }//GEN-LAST:event_btnActualizarMatriculaActionPerformed

    private void btnActualizarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAActionPerformed
        // TODO add your handling code here:
        if(txtAlumno.getText().length()>0 && txtNombre.getText().length()>0 && txtApellido.getText().length()>2 && txtEmail.getText().length()>0 && txtGenero.getText().length()>0){
        c.actualizarA(Integer.parseInt(txtAlumno.getText()),txtNombre.getText(), txtApellido.getText(), txtEmail.getText(), txtGenero.getText());
        }
    }//GEN-LAST:event_btnActualizarAActionPerformed

    private void btnActualizarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMateriaActionPerformed
        // TODO add your handling code here:
        if(txtMateria.getText().length()>0 && txtNombreMateria.getText().length()>0 && txtProfesorMateria.getText().length()>2 && txtCreditosMateria.getText().length()>0){
        c.actualizarM(Integer.parseInt(txtMateria.getText()),txtNombreMateria.getText(), txtProfesorMateria.getText(),txtCreditosMateria.getText());
        }
    }//GEN-LAST:event_btnActualizarMateriaActionPerformed

    private void btnEliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAActionPerformed
        // TODO add your handling code here:
        c.eliminar(Integer.parseInt(txtAlumno.getText()), null, null);
    }//GEN-LAST:event_btnEliminarAActionPerformed

    private void btnEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMateriaActionPerformed
        // TODO add your handling code here:
        c.eliminar(null, Integer.parseInt(txtMateria.getText()), null);
    }//GEN-LAST:event_btnEliminarMateriaActionPerformed

    private void btnEliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMActionPerformed
        // TODO add your handling code here:
        c.eliminar(null, null, Integer.parseInt(txtidMatricula.getText()));
    }//GEN-LAST:event_btnEliminarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alumno;
    private javax.swing.JPanel Materia;
    private javax.swing.JPanel Matricula;
    public javax.swing.JButton btnActualizarA;
    public javax.swing.JButton btnActualizarMateria;
    public javax.swing.JButton btnActualizarMatricula;
    public javax.swing.JButton btnBuscarA;
    public javax.swing.JButton btnBuscarMateria;
    public javax.swing.JButton btnBuscarMatricula;
    public javax.swing.JButton btnEliminarA;
    public javax.swing.JButton btnEliminarM;
    public javax.swing.JButton btnEliminarMateria;
    public javax.swing.JButton btnGuardarA;
    public javax.swing.JButton btnGuardarMateria;
    public javax.swing.JButton btnGuardarMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCreditosMateria;
    private javax.swing.JLabel lblFechaMatricula;
    private javax.swing.JLabel lblNameMateria;
    private javax.swing.JLabel lblProfesorMateria;
    private javax.swing.JLabel lbliDAlumnoMatricula;
    private javax.swing.JLabel lbliDMateria;
    private javax.swing.JLabel lbliDMateriaMatricula;
    private javax.swing.JLabel lbliDMatricula;
    public javax.swing.JTextField txtAlumno;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCreditosMateria;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtFechaMatricula;
    public javax.swing.JTextField txtGenero;
    public javax.swing.JTextField txtMateria;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreMateria;
    public javax.swing.JTextField txtProfesorMateria;
    public javax.swing.JTextField txtidAlumnoMatricula;
    public javax.swing.JTextField txtidMateriaMatricula;
    public javax.swing.JTextField txtidMatricula;
    // End of variables declaration//GEN-END:variables
}
